# Generated by Django 4.2.7 on 2023-12-15 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Specality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_file', models.FileField(blank=True, null=True, upload_to='stories/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('media_type', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('Dp', models.FileField(blank=True, null=True, upload_to='doctor/Dp')),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('others', 'others')], default='Male', max_length=100, null=True)),
                ('CurrentAddress', models.TextField(blank=True, null=True)),
                ('permanentAddress', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=18)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Degrees', models.FileField(blank=True, null=True, upload_to='doctor/certificate')),
                ('Diplomas', models.FileField(blank=True, null=True, upload_to='doctor/diploma')),
                ('References', models.TextField(blank=True, null=True)),
                ('Certificates', models.FileField(blank=True, null=True, upload_to='doctor/othercertificate')),
                ('RCI', models.TextField(blank=True, null=True)),
                ('PAN', models.FileField(blank=True, null=True, upload_to='doctor/PAN')),
                ('Aadhaar', models.FileField(blank=True, null=True, upload_to='doctor/Aadhaar')),
                ('GST', models.FileField(blank=True, null=True, upload_to='doctor/GST')),
                ('Aboutme', models.TextField(blank=True, null=True)),
                ('Education', models.TextField(blank=True, null=True)),
                ('Experience', models.CharField(blank=True, max_length=100, null=True)),
                ('callDuration', models.CharField(blank=True, default='30 Minutes', max_length=15, null=True)),
                ('Language', models.ManyToManyField(to='AdminSide.languages')),
                ('Specialization', models.ManyToManyField(to='AdminSide.specality')),
            ],
        ),
    ]
