# Generated by Django 4.2.7 on 2023-12-07 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('Dp', models.FileField(blank=True, null=True, upload_to='doctor/Dp')),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans', 'Trans')], default='Male', max_length=100, null=True)),
                ('CurrentAddress', models.TextField(blank=True, null=True)),
                ('permanentAddress', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(default='', max_length=18)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Degrees', models.FileField(blank=True, null=True, upload_to='doctor/certificate')),
                ('Diplomas', models.FileField(blank=True, null=True, upload_to='doctor/diploma')),
                ('References', models.TextField(blank=True, null=True)),
                ('Certificates', models.FileField(blank=True, null=True, upload_to='doctor/othercertificate')),
                ('RCI', models.TextField(blank=True, null=True)),
                ('PAN', models.FileField(blank=True, null=True, upload_to='doctor/PAN')),
                ('Aadhaar', models.FileField(blank=True, null=True, upload_to='doctor/Aadhaar')),
                ('GST', models.FileField(blank=True, null=True, upload_to='doctor/GST')),
                ('Aboutme', models.TextField(blank=True, null=True)),
                ('Education', models.TextField(blank=True, null=True)),
                ('Experience', models.CharField(blank=True, max_length=100, null=True)),
                ('callDuration', models.CharField(default='30 Minutes', max_length=15)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_file', models.FileField(blank=True, null=True, upload_to='stories/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
