# Generated by Django 4.2.7 on 2023-12-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='AdminSide.doctordata'),
        ),
    ]
