# Generated by Django 4.2.7 on 2023-12-14 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminSide', '0001_initial'),
        ('Trufrend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordata',
            name='VideoFavour',
            field=models.ManyToManyField(to='Trufrend.video'),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='story',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdminSide.stories'),
        ),
    ]
