# Generated by Django 4.2.7 on 2023-12-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminSide', '0001_initial'),
        ('Trufrend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordata',
            name='VideoFavour',
            field=models.ManyToManyField(to='Trufrend.video'),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='story',
            field=models.ManyToManyField(to='AdminSide.stories'),
        ),
    ]
