# Generated by Django 4.2.7 on 2023-12-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
