# Generated by Django 4.2.7 on 2023-12-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordata',
            name='callDuration',
        ),
    ]
