# Generated by Django 4.2.7 on 2023-12-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordata',
            name='story',
        ),
        migrations.AddField(
            model_name='doctordata',
            name='story',
            field=models.ManyToManyField(to='AdminSide.stories'),
        ),
    ]
