# Generated by Django 4.2.7 on 2023-12-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0002_stories_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordata',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('others', 'others')], default='Male', max_length=100, null=True),
        ),
    ]
