# Generated by Django 4.2.7 on 2023-12-22 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0003_remainder'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordata',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
