# Generated by Django 4.2.7 on 2023-12-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('DOB', models.DateField()),
                ('CurrentAddress', models.TextField()),
                ('permanentAddress', models.TextField()),
                ('phone', models.CharField(max_length=18)),
                ('Degrees', models.FileField(upload_to='doctor/certificate')),
                ('Diplomas', models.FileField(upload_to='doctor/diploma')),
                ('References', models.TextField()),
                ('Certificates', models.FileField(upload_to='doctor/othercertificate')),
                ('RCI', models.TextField()),
                ('PAN', models.FileField(upload_to='doctor/PAN')),
                ('Aadhaar', models.FileField(upload_to='doctor/Aadhaar')),
                ('GST', models.FileField(upload_to='doctor/GST')),
                ('Aboutme', models.TextField()),
                ('Education', models.TextField()),
                ('Experience', models.CharField(max_length=100)),
                ('callDuration', models.CharField(default='30 Minutes', max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
