# Generated by Django 4.2.7 on 2023-12-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0004_doctordata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='story_file',
            field=models.FileField(blank=True, default='', upload_to='stories/'),
        ),
    ]
