# Generated by Django 4.2.7 on 2023-12-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0004_doctordata_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordata',
            name='callDuration',
            field=models.CharField(blank=True, default='30 Minutes', max_length=15, null=True),
        ),
    ]
