# Generated by Django 4.2.7 on 2023-12-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0004_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='media_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
