# Generated by Django 4.2.7 on 2023-12-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0004_doctordata_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordata',
            name='Aadhaar',
            field=models.FileField(blank=True, null=True, upload_to='doctor/Aadhaar'),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='Aboutme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='Certificates',
            field=models.FileField(blank=True, null=True, upload_to='doctor/othercertificate'),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='CurrentAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='Degrees',
            field=models.FileField(blank=True, null=True, upload_to='doctor/certificate'),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='Diplomas',
            field=models.FileField(blank=True, null=True, upload_to='doctor/diploma'),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='Education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='Experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='GST',
            field=models.FileField(blank=True, null=True, upload_to='doctor/GST'),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='PAN',
            field=models.FileField(blank=True, null=True, upload_to='doctor/PAN'),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='RCI',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='References',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='permanentAddress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
