# Generated by Django 4.2.7 on 2023-12-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0005_alter_doctordata_aadhaar_alter_doctordata_aboutme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='doctordata',
            name='Dp',
            field=models.FileField(blank=True, null=True, upload_to='doctor/Dp'),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='language',
            field=models.ManyToManyField(to='AdminSide.languages'),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='specialization',
            field=models.ManyToManyField(to='AdminSide.specality'),
        ),
    ]
