# Generated by Django 4.2.7 on 2023-12-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0005_alter_stories_story_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordata',
            name='callDuration',
        ),
    ]
