# Generated by Django 4.2.7 on 2023-12-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0006_languages_specality_doctordata_dp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordata',
            name='language',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='specialization',
        ),
    ]
