# Generated by Django 4.2.7 on 2023-12-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0007_doctordata_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctordata',
            name='Specialization',
            field=models.ManyToManyField(to='AdminSide.specality'),
        ),
    ]
