# Generated by Django 4.2.7 on 2023-12-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0001_initial'),
        ('AdminSide', '0008_specality_doctordata_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordata',
            name='VideoFavour',
            field=models.ManyToManyField(to='Trufrend.video'),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='callDuration',
            field=models.CharField(blank=True, default='30 Minutes', max_length=15, null=True),
        ),
    ]
