# Generated by Django 4.2.7 on 2023-12-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0008_doctordata_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordata',
            name='Language',
            field=models.ManyToManyField(to='AdminSide.languages'),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='Specialization',
            field=models.ManyToManyField(to='AdminSide.specality'),
        ),
    ]
