# Generated by Django 4.2.7 on 2023-12-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0009_doctordata_language_doctordata_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordata',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
