# Generated by Django 4.2.7 on 2023-12-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0010_doctordata_email_doctordata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordata',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans', 'Trans')], default='Male', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
