# Generated by Django 4.2.7 on 2023-12-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0011_alter_doctordata_gender_alter_doctordata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specality',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
