# Generated by Django 4.2.7 on 2023-12-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0012_alter_specality_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='languages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
