# Generated by Django 4.2.7 on 2023-12-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('AdminSide', '0014_remove_doctordata_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordata',
            name='Aadhaar',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='Aboutme',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='Certificates',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='CurrentAddress',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='Degrees',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='Diplomas',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='Education',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='GST',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='PAN',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='RCI',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='References',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='callDuration',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='permanentAddress',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='phone',
        ),
        migrations.AddField(
            model_name='doctordata',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='doctordata',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
