# Generated by Django 4.2.7 on 2023-12-06 05:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0018_languages_specality_doctordata_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_file', models.FileField(upload_to='stories/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.DeleteModel(
            name='Specality',
        ),
        migrations.AddField(
            model_name='doctordata',
            name='stories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminSide.stories'),
        ),
    ]
