# Generated by Django 4.2.7 on 2023-11-29 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField()),
                ('CurrentAddress', models.TextField()),
                ('permanentAddress', models.TextField()),
                ('phone', models.CharField(max_length=18)),
                ('Degrees', models.FileField(upload_to='doctor/certificate')),
                ('Diplomas', models.FileField(upload_to='doctor/diploma')),
                ('References', models.TextField()),
                ('Certificates', models.FileField(upload_to='doctor/othercertificate')),
                ('RCI', models.TextField()),
                ('PAN', models.FileField(upload_to='doctor/PAN')),
                ('Aadhaar', models.FileField(upload_to='doctor/Aadhaar')),
                ('GST', models.FileField(upload_to='doctor/GST')),
                ('Aboutme', models.TextField()),
                ('Education', models.TextField()),
                ('Experience', models.CharField(max_length=15)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Malayalam', 'Malayalam'), ('Tamil', 'Tamil')], max_length=100)),
                ('callDuration', models.CharField(default='30 Minutes', max_length=15)),
                ('specialties', models.ManyToManyField(to='AdminPanel.specialty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
