# Generated by Django 4.2.7 on 2023-11-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0002_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Languages', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='Experience',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='doctordetail',
            name='language',
        ),
        migrations.AlterField(
            model_name='specialty',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='doctordetail',
            name='language',
            field=models.ManyToManyField(to='AdminPanel.language'),
        ),
    ]
