# Generated by Django 4.2.7 on 2023-11-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0003_language_alter_doctordetail_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetail',
            name='language',
            field=models.ManyToManyField(blank=True, null=True, to='AdminPanel.language'),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='specialties',
            field=models.ManyToManyField(blank=True, null=True, to='AdminPanel.specialty'),
        ),
        migrations.AlterField(
            model_name='language',
            name='Languages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
