# Generated by Django 4.2.7 on 2023-11-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0007_alter_doctordetail_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='Languages',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='specialization',
            field=models.CharField(default='', max_length=100),
        ),
    ]
