# Generated by Django 4.2.7 on 2023-11-01 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenges', models.CharField(choices=[('Anxiety', 'Anxiety'), ('Motivation', 'Motivation'), ('Confidence', 'Confidence'), ('Sleep', 'Sleep'), ('Depression', 'Depression'), ('Work Stress', 'Work Stress'), ('Relationships', 'Relationships'), ('Exam stress', 'Exam stress'), ('Pregnancy', 'Pregnancy'), ('Loss', 'Loss'), ('LGBTQ+', 'LGBTQ+'), ('Low Energy', 'Low Energy'), ('Self Esteem', 'Self Esteem'), ('Loneliness', 'Loneliness'), ('Trauma', 'Trauma'), ('Health issues', 'Health issues')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_file', models.FileField(upload_to='videos/video_pack')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(blank=True, null=True, upload_to='img/profile_pictures')),
                ('name', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=50)),
                ('age', models.TextField(blank=True, choices=[('13-17 years old', '13-17 years old'), ('18 Years and old', '18 Years and old')], null=True)),
                ('SOS', models.CharField(blank=True, max_length=15, unique=True)),
                ('challenges', models.ManyToManyField(to='Trufrend.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
