# Generated by Django 4.2.7 on 2023-12-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('videoFavour', models.ManyToManyField(to='Trufrend.video')),
            ],
        ),
    ]
