# Generated by Django 4.2.7 on 2024-01-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0002_initial'),
        ('Trufrend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recent_calls',
            field=models.ManyToManyField(related_name='recent_calls_of_user', to='AdminSide.doctordata'),
        ),
    ]
