# Generated by Django 4.2.7 on 2023-12-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0002_videofavourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
