# Generated by Django 4.2.7 on 2023-12-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0003_remainder'),
        ('Trufrend', '0002_profile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recent_calls',
            field=models.ManyToManyField(related_name='recent_calls_of_user', to='AdminSide.doctordata'),
        ),
    ]
