# Generated by Django 4.2.7 on 2024-01-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0002_profile_recent_calls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='recent_calls',
        ),
    ]
