# Generated by Django 4.2.7 on 2023-11-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0003_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='SOS',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
