# Generated by Django 4.2.7 on 2024-01-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0003_remove_profile_recent_calls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Not_Selected', 'Not_Selected'), ('Male', 'Male'), ('Female', 'Female'), ('others', 'others')], default='Not_Selected', max_length=100, null=True),
        ),
    ]
