# Generated by Django 4.2.7 on 2023-12-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0003_alter_profile_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoFavourite',
        ),
    ]
