# Generated by Django 4.2.7 on 2023-12-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0003_profile_recent_calls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='DOB',
        ),
    ]
