# Generated by Django 4.2.7 on 2023-11-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0004_alter_profile_sos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='SOS',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
