# Generated by Django 4.2.7 on 2023-11-07 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0005_remove_profile_sos_remove_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='parent_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_videos', to='Trufrend.video'),
        ),
    ]
