# Generated by Django 4.2.7 on 2023-12-08 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0004_quotes'),
        ('Trufrend', '0006_profile_doctorfavour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminSide.doctordata')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trufrend.profile')),
            ],
        ),
    ]
