# Generated by Django 4.2.7 on 2023-11-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0007_videopack_remove_video_parent_video_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
