# Generated by Django 4.2.7 on 2023-12-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0009_usercount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usercount',
        ),
    ]
