# Generated by Django 4.2.7 on 2023-12-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0010_delete_usercount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usercount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_count', models.IntegerField()),
            ],
        ),
    ]
