# Generated by Django 4.2.7 on 2023-12-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0011_usercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercount',
            name='user_count',
            field=models.CharField(max_length=10),
        ),
    ]
