# Generated by Django 4.2.7 on 2023-11-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0011_alter_profile_phone_number_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
