# Generated by Django 4.2.7 on 2023-11-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0012_remove_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenges',
            field=models.CharField(max_length=100),
        ),
    ]
