# Generated by Django 4.2.7 on 2023-11-13 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0013_alter_challenge_challenges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='challenges',
        ),
        migrations.AddField(
            model_name='profile',
            name='challenges',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Trufrend.challenge'),
        ),
    ]
