# Generated by Django 4.2.7 on 2023-12-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0013_alter_usercount_user_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
