# Generated by Django 4.2.7 on 2023-11-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0016_remove_profile_challenges_profile_challenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='challenges',
            field=models.ManyToManyField(blank=True, null=True, to='Trufrend.challenge'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=True, max_length=15),
        ),
    ]
