# Generated by Django 4.2.7 on 2023-11-20 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0017_alter_profile_challenges_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='profile',
            name='challenges',
            field=models.ManyToManyField(to='Trufrend.challenge'),
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trufrend.video')),
            ],
        ),
    ]
