# Generated by Django 4.2.7 on 2023-11-20 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0018_remove_video_video_file_alter_profile_challenges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='', upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_pack',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Trufrend.videopack'),
        ),
        migrations.DeleteModel(
            name='VideoFile',
        ),
    ]
