# Generated by Django 4.2.7 on 2023-11-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0019_remove_video_title_video_video_file_video_video_pack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopack',
            name='video_file',
            field=models.FileField(default='', upload_to='videos/'),
        ),
    ]
