# Generated by Django 4.2.7 on 2023-11-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0020_videopack_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_pack',
        ),
        migrations.RemoveField(
            model_name='videopack',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Trufrend.videopack'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
