# Generated by Django 4.2.7 on 2023-11-20 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0021_remove_video_video_pack_remove_videopack_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trufrend.videopack'),
        ),
    ]
