# Generated by Django 4.2.7 on 2023-11-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0023_remove_video_video_file_remove_videopack_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_files',
        ),
        migrations.RemoveField(
            model_name='videopack',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='', upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='videopack',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='videopack',
            name='video_files',
            field=models.ManyToManyField(related_name='video_packs', to='Trufrend.video'),
        ),
    ]
