# Generated by Django 4.2.7 on 2023-11-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0024_remove_video_title_remove_video_video_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopack',
            name='title',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
