# Generated by Django 4.2.7 on 2023-11-21 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0025_alter_videopack_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Trufrend.videopack'),
        ),
    ]
