# Generated by Django 4.2.7 on 2023-11-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0027_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopack',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
