# Generated by Django 4.2.7 on 2023-11-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0028_alter_videopack_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='videopack',
            name='title',
        ),
        migrations.RemoveField(
            model_name='videopack',
            name='video_files',
        ),
        migrations.AddField(
            model_name='video',
            name='video_files',
            field=models.ManyToManyField(to='Trufrend.videopack'),
        ),
        migrations.AddField(
            model_name='videopack',
            name='video_file',
            field=models.FileField(default='', upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
