# Generated by Django 4.2.7 on 2023-11-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0034_alter_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=True, max_length=15),
        ),
    ]
