# Generated by Django 4.2.7 on 2023-11-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0035_remove_favorite_user_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='posterimage',
            field=models.ImageField(blank=True, null=True, upload_to='img/Posterimage'),
        ),
        migrations.AddField(
            model_name='videopack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/videobanner'),
        ),
        migrations.AddField(
            model_name='videopack',
            name='subtitle',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
