# Generated by Django 4.2.7 on 2023-11-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0036_video_posterimage_videopack_image_videopack_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.AddField(
            model_name='videopack',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
