# Generated by Django 4.2.7 on 2023-11-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0037_remove_video_description_videopack_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopack',
            name='videolen',
            field=models.CharField(default='10', max_length=100),
        ),
        migrations.AlterField(
            model_name='videopack',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
