# Generated by Django 4.2.7 on 2023-11-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0038_videopack_videolen_alter_videopack_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_file', models.FileField(upload_to='stories/')),
            ],
        ),
    ]
