# Generated by Django 4.2.7 on 2023-11-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0039_stories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stories',
        ),
    ]
