# Generated by Django 4.2.7 on 2023-11-23 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0040_delete_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=254)),
                ('subject', models.TextField()),
                ('description', models.TextField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trufrend.profile')),
            ],
        ),
    ]
