# Generated by Django 4.2.7 on 2023-11-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0041_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='phone',
        ),
    ]
