# Generated by Django 4.2.7 on 2023-11-23 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0042_remove_contactus_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Trufrend.profile'),
        ),
    ]
