# Generated by Django 4.2.7 on 2023-11-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0044_alter_contactus_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
