# Generated by Django 4.2.7 on 2023-11-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trufrend', '0045_rename_phone_contactus_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='phone_number',
            new_name='phone_no',
        ),
    ]
