# Generated by Django 4.2.7 on 2024-01-01 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminSide', '0002_initial'),
        ('Trufrend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminSide.doctordata')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trufrend.profile')),
            ],
        ),
    ]
