# Generated by Django 4.2.7 on 2024-01-06 19:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminSide', '0002_initial'),
        ('Trufrend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('couselor_reply', models.TextField(blank=True, default='')),
                ('counselor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdminSide.doctordata')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Trufrend.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernickname', models.CharField(default='', max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminSide.doctordata')),
            ],
        ),
    ]
