# Generated by Django 4.2.7 on 2024-01-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='profile',
        ),
    ]
