# Generated by Django 4.2.7 on 2024-01-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_remove_feedback_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='usernickname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
