# Generated by Django 4.2.7 on 2024-01-03 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_feedback_usernickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
